### ISSUE TITLE
Engine - Install Rancher - Stateful

### ISSUE THREAD

**Issue by sgnd** [cloudboz/cloudboz#28]
Expect behavior:
1. Running with ansible docker
2. Create docker volume for the container `{container-name}-data`
3. Connect a container to default network `cloudboz-network`

**Comment by ledleledle** [comment]
Helo @sgnd. i can't really test this assignment, because my laptop always freeze when rancher started, maybe i can create PR and you can tested my ansible script.

Thank you

**Comment by ledleledle** [comment]
sorry nevermind, it's just freeze when i open ssh XD

**Comment by sgnd** [comment]
Haha that's ok
